# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-api-feed mohlin/udagram-api-feed:v1
    - run: docker tag udagram-api-user mohlin/udagram-api-user:v1
    - run: docker tag reverseproxy mohlin/reverseproxy:v1
    - run: docker tag dagram-frontend:local mohlin/udagram-frontend:v1
    - run: echo "${{secrets.DOCKER_USERNAME}}" | docker login -u "${{secrets.DOCKER_PASSWORD}}" --password-stdin
    - run: docker push udagram-api-feed:v1
    - run: docker push udagram-api-user:v1
    - run: docker push reverseproxy:v1
    - run: docker push udagram-frontend:v1
    

